version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-codedeploy
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/compose-down.sh
    - location: scripts/compose-build.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/compose-up.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/compose-down.sh
      timeout: 300
      runas: ubuntu