version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-app

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/compose-down.sh
      timeout: 10
      runas: ubuntu

  AfterInstall:
    - location: scripts/compose-build.sh
      timeout: 1200
      runas: ubuntu

  ApplicationStart:
    - location: scripts/compose-up.sh
      timeout: 60
      runas: ubuntu