version: '3' # specify docker-compose version

# Define the services/containers to be run
services:

 angular:
   build:
     context: ./angularClient
     dockerfile: DOCKERFILE
   ports:
     - "80:4200"

 node: # name of the first service
   build:  # specify the directory of the Dockerfile
      context: ./nodeServer
      dockerfile: DOCKERFILE
   ports:
     - "8080:8080"
   environment:
     - MONGO_URL=mongodb://database/mean-app
   links:
     - mongodb
   depends_on:
     - mongodb

 mongodb: # name of the third service
   image: mongo # specify image to build container from
   volumes:
     - "/data/db:/data/db"
   ports:
     - "27017:27017" # specify port forewarding
