version: '3'
services:
  angular_client:
    build: ./angularClient
    ports:
      - "4200:4200"

  api:
    build: ./mongoApi
    ports:
      - "8181:8181"

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - './database/data:/data/db'

volumes:
  mongo-volume:
