name: Deploy to EC2

on:
  push:
    branches:
      - master
  #pull_request:
  #  types: [closed]
jobs:
  ssh-deploy:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          command_timeout: 30m
          script: ./deploy-todo.sh
