name: CI test

on:
  push:
   branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Test API
      working-directory: back
      run: |
        npm install
        echo 'Finished back install'
        npm test
        echo 'Finished tests'
        npm start &
    
    - name: Launch front for cypress
      working-directory: front
      run: |
        npm install
        (npm start &)
      
    - name: Wait a bit for server spool-up
      uses: jakejarvis/wait-action@master
      with:
        time: '10s' 
        
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: front
        wait-on: 'http://localhost:4200'
        wait-on-timeout: 60
