name: Tests front

on:
  push:
   branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start API
      working-directory: back
      run: |
        npm install
        npm start &
        
    - name: Install Front
      working-directory: front
      run: |
        npm install
        npm install -g @angular/cli
        
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: front
        start: ng serve
        wait-on: 'http://localhost:4200'
        wait-on-timeout: 60
